### ISSUE TITLE
telegram.error.Unauthorized: Forbidden: bot can't initiate conversation with a user

### ISSUE THREAD

**Issue by pongo** [pongo/rapturebot#78]
Найди все случаи когда он отправляет сообщение в личку и обернуть все при помощи try.

Ошибка: `telegram.error.Unauthorized: Forbidden: bot can't initiate conversation with a user`

**Comment by pongo** [comment]
Судя по всему, ошибка происходит когда после `/leave` нажимают кнопку "Показать последние слова". Вероятно запросивший или не открывал еще диалог с ботом, или забанил бота.

Но проблема в том, что весь этот метод покрыт проверками на исключения. А в логах нет ничего конкретного:

```
[2018-09-13 19:14:19,616][ERROR] - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/home/rapture/rapturebot/venv/lib/python3.6/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/rapture/rapturebot/src/bot_start/mqbot.py", line 58, in sendMessage
    return super(MQBot, self).send_message(*args, **kwargs)
  File "/home/rapture/rapturebot/venv/lib/python3.6/site-packages/telegram/bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "/home/rapture/rapturebot/venv/lib/python3.6/site-packages/telegram/bot.py", line 85, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/rapture/rapturebot/venv/lib/python3.6/site-packages/telegram/utils/request.py", line 278, in post
    **urlopen_kwargs)
  File "/home/rapture/rapturebot/venv/lib/python3.6/site-packages/telegram/utils/request.py", line 213, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Forbidden: bot can't initiate conversation with a user
```

Вероятнее всего проблема в питоновской библиотеке https://github.com/python-telegram-bot/python-telegram-bot/issues/682
